<?php
const SERVER_URL = 'http://localhost/warrax';
const MONTHS = [
    [ 'val' =>  1, 'name' => 'Январь' ],
    [ 'val' => 2, 'name' => 'Февраль' ],
    [ 'val' => 3, 'name' => 'Март' ],
    [ 'val' => 4, 'name' => 'Апрель' ],
    [ 'val' => 5, 'name' => 'Май' ],
    [ 'val' => 6, 'name' => 'Июнь' ],
    [ 'val' => 7, 'name' => 'Июль' ],
    [ 'val' => 8, 'name' => 'Август' ],
    [ 'val' => 9, 'name' => 'Сентябрь' ],
    [ 'val' => 10, 'name' => 'Октябрь' ],
    [ 'val' => 11, 'name' => 'Ноябрь' ],
    [ 'val' => 12, 'name' => 'Декабрь' ],
];
const DAYS = [
    [ 'val' =>  1, 'name' => '01' ],
    [ 'val' => 2, 'name' => '02' ],
    [ 'val' => 3, 'name' => '03' ],
    [ 'val' => 4, 'name' => '04' ],
    [ 'val' => 5, 'name' => '05' ],
    [ 'val' => 6, 'name' => '06' ],
    [ 'val' => 7, 'name' => '07' ],
    [ 'val' => 8, 'name' => '08' ],
    [ 'val' => 9, 'name' => '09' ],
    [ 'val' => 10, 'name' => '10' ],
    [ 'val' => 11, 'name' => '11' ],
    [ 'val' => 12, 'name' => '12' ],
    [ 'val' => 13, 'name' => '13' ],
    [ 'val' => 14, 'name' => '14' ],
    [ 'val' => 15, 'name' => '15' ],
    [ 'val' => 16, 'name' => '16' ],
    [ 'val' => 17, 'name' => '17' ],
    [ 'val' => 18, 'name' => '18' ],
    [ 'val' => 19, 'name' => '19' ],
    [ 'val' => 20, 'name' => '20' ],
    [ 'val' => 21, 'name' => '21' ],
    [ 'val' => 22, 'name' => '22' ],
    [ 'val' => 23, 'name' => '23' ],
    [ 'val' => 24, 'name' => '24' ],
    [ 'val' => 25, 'name' => '25' ],
    [ 'val' => 26, 'name' => '26' ],
    [ 'val' => 27, 'name' => '27' ],
    [ 'val' => 28, 'name' => '28' ],
    [ 'val' => 29, 'name' => '29' ],
    [ 'val' => 30, 'name' => '30' ],
    [ 'val' => 31, 'name' => '31' ]
];
?>